### ISSUE TITLE
JANUS_PLUGIN_API_VERSION without refcount feature

### ISSUE THREAD

**Issue by ivanovaleksey** [mozilla/janus-plugin-rs#8]
Hello @mquander,

I have faced with a little problem with my EchoTest plugin.
Today I rebuild a Docker image and apparently Janus Gateway source code was updated.
As it turns out `JANUS_PLUGIN_API_VERSION` was [bumped](https://github.com/meetecho/janus-gateway/commit/77bcaa7f0de6cf681ea6fbdb4e55e4b02dfddd0b) from `8` to `9`.

Currently I use `0.7.1` version without `refcount` feature.
In [that case](https://github.com/mozilla/janus-plugin-rs/blob/v0.7.1/janus-plugin-sys/src/lib.rs#L13) `JANUS_PLUGIN_API_VERSION = 8`.

I got the following error.
```
[ERR] [janus.c:main:3912] The 'janus.plugin.echotest' plugin was compiled against an older version of the API (8 < 9), skipping it: update it to enable it again
```

It is not a problem really since the plugin is demo-only and could be easily build using `refcount`.
I would like to ask you for advice.
Janus Gateway already defined new `9` API version on _master_ not _refcount_ branch.
And the crate expects that `9` could be only on _refcount_ branch.
Should we change it somehow?

**Comment by mqp** [comment]
Hmm. I think the plugin versions are not doing a good job of unambiguously indicating the features the plugin is supposed to support -- for example, [this change](https://github.com/mozilla/janus-plugin-rs/blob/master/janus-plugin-sys/src/lib.rs#L43) matches a gateway change in the refcount branch, concurrently with the version being bumped to 9 in that branch, but now the master has bumped the version to 9 without including that change. So 9 means one thing in the refcount branch and another thing in master.

Regardless, it doesn't seem like this library should be opinionated about the plugin version, anyway. This library is just a set of tools for making a plugin -- you can use them to make a plugin that is compatible with this version or that version. So I'm inclined to change it to just leave it up to your plugin code to decide what your plugin's API version is. Does that sound reasonable to you?

See https://github.com/mozilla/janus-plugin-rs/pull/9.

**Comment by ivanovaleksey** [comment]
It would be nice to get an answer to [your comment](https://github.com/meetecho/janus-gateway/pull/403#issuecomment-357358455) on _refcount_ PR, whether it is just a mistake or not.
It was convenient just to have `JANUS_PLUGIN_API_VERSION` defined while it was unambiguous.
But now it looks more like a problem than a helper.
Anyway, it is not a big deal to define API version in plugin's code manually.

**Comment by mqp** [comment]
(This is changed as suggested above in 0.8.0.)
